<?php

namespace Hyper\DomainBundle\Repository\Identity;

use Doctrine\ORM\EntityRepository;
use Hyper\Domain\Identity\IdentityRepository;
use Hyper\Domain\Identity\Identity;

/**
 * IdentityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DTIdentityRepository extends EntityRepository implements IdentityRepository
{
    
}