<?php

namespace Hyper\DomainBundle\Repository\Action;

use Doctrine\ORM\EntityRepository;
use Hyper\Domain\Action\AddToCartActionRepository;
use Hyper\Domain\Action\AddToCartAction;

/**
 * AddToWishlistActionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DTAddToCartActionRepository extends EntityRepository implements AddToCartActionRepository
{

}