<?php

namespace Hyper\DomainBundle\Repository\Action;

use Doctrine\ORM\EntityRepository;
use Hyper\Domain\Action\AddToWishlistActionRepository;
use Hyper\Domain\Action\AddToWishlistAction;

/**
 * AddToWishlistActionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DTAddToWishlistActionRepository extends EntityRepository implements AddToWishlistActionRepository
{
    public function save(AddToWishlistAction $addToWishlistAction){
        $this->_em->persist($addToWishlistAction);
        //$this->_em->flush();
    }
    
    public function completeTransaction(){
        $this->_em->flush();
        $this->_em->clear();
    }
    
    public function closeConnection(){
        $this->_em->close();
    }
    
}