<?php

namespace Hyper\DomainBundle\Repository\Action;

use Doctrine\ORM\EntityRepository;
use Hyper\Domain\Action\AddToCartActionRepository;
use Hyper\Domain\Action\AddToCartAction;

/**
 * AddToWishlistActionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DTAddToCartActionRepository extends EntityRepository implements AddToCartActionRepository
{
    public function save(AddToCartAction $addToCartAction){
        $this->_em->persist($addToCartAction);
        //$this->_em->flush();
    }
    
    public function completeTransaction(){
        $this->_em->flush();
        $this->_em->clear();
    }
    
    public function closeConnection(){
        $this->_em->close();
    }
}