<?php

namespace Hyper\DomainBundle\Repository\Action;

use Doctrine\ORM\EntityRepository;
use Hyper\Domain\Action\AddToWishlistActionRepository;
use Hyper\Domain\Action\AddToWishlistAction;

/**
 * AddToWishlistActionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DTAddToWishlistActionRepository extends EntityRepository implements AddToWishlistActionRepository
{

}