<?php

namespace Hyper\DomainBundle\Repository\Action;

use Doctrine\ORM\EntityRepository;
use Hyper\Domain\Action\InstallActionRepository;
use Hyper\Domain\Action\InstallAction;

/**
 * InstallActionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DTInstallActionRepository extends EntityRepository implements InstallActionRepository
{

}