<?php

namespace Hyper\DomainBundle\Repository\Action;

use Doctrine\ORM\EntityRepository;
use Hyper\Domain\Action\LaunchActionRepository;
use Hyper\Domain\Action\LaunchAction;

/**
 * LaunchActionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DTLaunchActionRepository extends EntityRepository implements LaunchActionRepository
{
    public function save(LaunchAction $launchAction){
        $this->_em->persist($launchAction);
        //$this->_em->flush();
    }
    
    public function completeTransaction(){
        $this->_em->flush();
        $this->_em->clear();
    }
    
    public function closeConnection(){
        $this->_em->close();
    }
    
}