<?php

namespace Hyper\DomainBundle\Repository\Action;

use Doctrine\ORM\EntityRepository;
use Hyper\Domain\Action\SearchActionRepository;
use Hyper\Domain\Action\SearchAction;

/**
 * SearchActionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DTSearchActionRepository extends EntityRepository implements SearchActionRepository
{
    public function save(SearchAction $searchAction) {
        //\Doctrine\Common\Util\Debug::dump($searchAction);
        $this->_em->persist($searchAction);
        //echo "search action persisted";
        //$this->_em->flush();
    }
    
    public function completeTransaction() {
        $this->_em->flush();
        $this->_em->clear();
    }
    
    public function closeConnection() {
        $this->_em->close();
    }
}