<?php

namespace Hyper\DomainBundle\Repository\Action;

use Doctrine\ORM\EntityRepository;
use Hyper\Domain\Action\SearchActionRepository;
use Hyper\Domain\Action\SearchAction;

/**
 * SearchActionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DTSearchActionRepository extends EntityRepository implements SearchActionRepository
{

}