<?php

namespace Hyper\DomainBundle\Repository\Action;

use Doctrine\ORM\EntityRepository;
use Hyper\Domain\Action\ShareContentActionRepository;
use Hyper\Domain\Action\ShareContentAction;

/**
 * ShareContentActionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DTShareContentActionRepository extends EntityRepository implements ShareContentActionRepository
{
    public function save(ShareContentAction $shareContentAction){
        $this->_em->persist($shareContentAction);
        //$this->_em->flush();
    }
    
    public function completeTransaction(){
        $this->_em->flush();
        $this->_em->clear();
    }
    
    public function closeConnection(){
        $this->_em->close();
    }
}