<?php

namespace Hyper\DomainBundle\Repository\Action;

use Doctrine\ORM\EntityRepository;
use Hyper\Domain\Action\TransactionActionRepository;
use Hyper\Domain\Action\TransactionAction;

/**
 * AddToWishlistActionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DTTransactionActionRepository extends EntityRepository implements TransactionActionRepository
{

}