<?php

namespace Hyper\DomainBundle\Repository\Action;

use Doctrine\ORM\EntityRepository;
use Hyper\Domain\Action\ViewContentActionRepository;
use Hyper\Domain\Action\ViewContentAction;

/**
 * viewContentActionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DTViewContentActionRepository extends EntityRepository implements ViewContentActionRepository
{
    public function save(ViewContentAction $viewContentAction){
        $this->_em->persist($viewContentAction);
        //$this->_em->flush();
    }
    
    public function completeTransaction(){
        $this->_em->flush();
        $this->_em->clear();
    }
    
    public function closeConnection(){
        $this->_em->close();
    }
}