<?php

namespace Hyper\DomainBundle\Repository\Device;

use Doctrine\ORM\EntityRepository;
use Hyper\Domain\Device\AndroidDeviceRepository;
use Hyper\Domain\Device\Device;
use Hyper\Domain\Device\AndroidDevice;

/**
 * DeviceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DTAndroidDeviceRepository extends EntityRepository implements AndroidDeviceRepository
{

}