<?php

namespace Hyper\DomainBundle\Repository\Device;

use Doctrine\ORM\EntityRepository;
use Hyper\Domain\Device\DeviceRepository;
use Hyper\Domain\Device\Device;

/**
 * DeviceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DTDeviceRepository extends EntityRepository implements DeviceRepository
{
    public function add (Device $device){
        $this->_em->persist($device);
        //$this->_em->flush();
    }
}