<?php

namespace Hyper\DomainBundle\Repository\Device;

use Doctrine\ORM\EntityRepository;
use Hyper\Domain\Device\IOSDeviceRepository;
use Hyper\Domain\Device\Device;
use Hyper\Domain\Device\IOSDevice;

/**
 * IOSDeviceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DTIOSDeviceRepository extends EntityRepository implements IOSDeviceRepository
{

}