<?php

namespace Hyper\DomainBundle\Repository\Push;

use Doctrine\ORM\EntityRepository;
use Hyper\Domain\Push\PushRepository;
use Hyper\Domain\Push\Push;

/**
 * PushRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DTPushRepository extends EntityRepository implements PushRepository
{
    public function save(Push $push){
        $this->_em->persist($push);
    }
    
    public function completeTransaction(){        
        $this->_em->flush();        
    }
        
    public function findUser($user, $email)
    {
        $user = $this->findOneBy(
            array('username' => $user, 'email' => $email)
         );
        
        return $user;
    }
    
    public function findbyCriteria($field, $value)
    {
        $record = $this->findOneBy(array($field => $value));
        return $record;
    }
    
    public function getResultAndCount($page, $rpp)
    {
        $countQuery = $this->createQueryBuilder('au')->select('count(au.id)')->getQuery();
        $totalRows = $countQuery->getSingleScalarResult();

        $query = $this->createQueryBuilder('au')->select('au')->orderBy('au.created', 'DESC')->getQuery();
        $offset = $rpp*($page-1);
        $rows = $query->setFirstResult($offset)->setMaxResults($rpp)->getResult(\Doctrine\ORM\Query::HYDRATE_OBJECT);
        return array(
            'rows' => $rows,
            'total' => $totalRows
        );
    }
    
    public function getLastRecord()
    {
        $query = $this->createQueryBuilder('push')->select('push')->orderBy('push.created', 'DESC')->getQuery();
        $row = $query->setMaxResults(1)->getSingleResult(\Doctrine\ORM\Query::HYDRATE_OBJECT);
        return $row;
    }
    
    public function updateJsonFile($id, $json, $success, $fail, $callback, $update_time)
    {
        $user = $this->findOneBy(
            array('id' => $id)
        );
        
        $count = count($user);
        
        if($count > 0)
        {
            $user->setJsonFile("$json");
            $user->setSuccess($success);
            $user->setFail($fail);
            $user->setCallback("$callback");
            $user->setUpdated($update_time);
            $this->_em->flush();
            
            return "success";
        }        
        else
        {
            return "failed";
        }
    }
}