<?php

namespace Hyper\DomainBundle\Repository\Promo_landing;

use Doctrine\ORM\EntityRepository;
use Hyper\Domain\Promo_landing\PromoLandingRepository;
use Hyper\Domain\Promo_landing\PromoLanding;

/**
 * PromoLandingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DTPromoLandingRepository extends EntityRepository implements PromoLandingRepository
{
    public function save(PromoLanding $promo_landing){
        $this->_em->persist($promo_landing);
    }
    
    public function completeTransaction(){        
        $this->_em->flush();        
    }
        
    
    public function findbyCriteria($field, $value)
    {
        $record = $this->findOneBy(array($field => $value));
        return $record;
    }
    
    public function getResultAndCount($page, $rpp)
    {
        $countQuery = $this->createQueryBuilder('pr')->select('count(pr.id)')->getQuery();
        $totalRows = $countQuery->getSingleScalarResult();

        $query = $this->createQueryBuilder('pr')->select('pr')->orderBy('pr.created', 'DESC')->getQuery();
        $offset = $rpp*($page-1);
        $rows = $query->setFirstResult($offset)->setMaxResults($rpp)->getResult(\Doctrine\ORM\Query::HYDRATE_OBJECT);
        return array(
            'rows' => $rows,
            'total' => $totalRows
        );
    }
    
    public function getLastRecord()
    {
        $query = $this->createQueryBuilder('promo')->select('promo')->orderBy('promo.created', 'DESC')->getQuery();
        $row = $query->setMaxResults(1)->getSingleResult(\Doctrine\ORM\Query::HYDRATE_OBJECT);
        return $row;
    }
    
    public function updateDeepLinkMap($appId, $deeplink)
    {
        $deeplink_map = $this->findOneBy(
            array('appId' => $appId)
        );
        
        $count = count($deeplink_map);
        
        if($count > 0)
        {
            $deeplink_map->setDeeplinkMap($deeplink);
            $this->_em->flush();
            
            return "success";
        }        
        else
        {
            return "failed";
        }
    }
    
    public function getAllRecords()
    {
        $record = $this->findAll();
        return $record;
    }
}