<?php

namespace Hyper\DomainBundle\Repository\Item;

use Doctrine\ORM\EntityRepository;
use Hyper\Domain\Item\InCartItemRepository;
use Hyper\Domain\Item\InCartItem;

/**
 * InCartItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DTInCartItemRepository extends EntityRepository implements InCartItemRepository
{
    public function save(InCartItem $inCartItem){
        $this->_em->persist($inCartItem);
        //$this->_em->flush();
        echo "<hr/>"."incartitem persisted";
    }
}