<?php

namespace Hyper\DomainBundle\Repository\Item;

use Doctrine\ORM\EntityRepository;
use Hyper\Domain\Item\InWishlistItemRepository;
use Hyper\Domain\Item\InWishlistItem;

/**
 * InWishlistItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DTInWishlistItemRepository extends EntityRepository implements InWishlistItemRepository
{
    
}