<?php

namespace Hyper\DomainBundle\Repository\Item;

use Doctrine\ORM\EntityRepository;
use Hyper\Domain\Item\InCategoryItemRepository;
use Hyper\Domain\Item\InCategoryItem;

/**
 * InCartItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DTInCategoryItemRepository extends EntityRepository implements InCategoryItemRepository
{
    public function save(InCategoryItem $inCategoryItem){
        $this->_em->persist($inCategoryItem);
        //$this->_em->flush();
        echo "<hr/>"."InCategoryItem persisted";
    }
    
    public function getByIdentifier($identifier){
        if (
            !array_key_exists('item_code',$identifier)
             ||
            !array_key_exists('category_id',$identifier)
        ) {
            throw new \Exception('invalid item in category identifier');
        }
        $inCategoryItem = $this->getByCategoryAndItemCode(
            $identifier['item_code'],
            $identifier['category_id']
        );
        return $inCategoryItem;
    }
    
    public function getByCategoryAndItemCode($itemCode,$categoryId){
        return $this->findOneBy(
                    array(
                        'itemCode' => $itemCode,
                        'category' => $categoryId
                    )
                );
    }
    
}