<?php

namespace Hyper\DomainBundle\Repository\Item;

use Doctrine\ORM\EntityRepository;
use Hyper\Domain\Item\ItemRepository;
use Hyper\Domain\Item\Item;

/**
 * ItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DTItemRepository extends EntityRepository implements ItemRepository
{
    
}