<?php

namespace Hyper\DomainBundle\Repository\Item;

use Doctrine\ORM\EntityRepository;
use Hyper\Domain\Item\TransactedItemRepository;
use Hyper\Domain\Item\TransactedItem;

/**
 * TransactedItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DTTransactedItemRepository extends EntityRepository implements TransactedItemRepository
{
    
}