<?php

namespace Hyper\DomainBundle\Repository\DeviceAppInformation;

use Doctrine\ORM\EntityRepository;
use Hyper\Domain\DeviceAppInformation\DeviceAppInformationRepository;

/**
 * DTDeviceAppInformationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DTDeviceAppInformationRepository extends EntityRepository implements DeviceAppInformationRepository
{

}