<?php

namespace Hyper\DomainBundle\Repository\Setting;

use Doctrine\ORM\EntityRepository;
use Hyper\Domain\Setting\SettingRepository;
use Hyper\Domain\Setting\Setting;

/**
 * SettingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DTSettingRepository extends EntityRepository implements SettingRepository
{
    public function save(Setting $setting){
        $this->_em->persist($setting);
        //echo "saved";
        //$this->_em->flush();
    }
    
    public function completeTransaction(){
        //echo "flushing";
        $this->_em->flush();
        //echo "flushed";
    }
    
    public function remove(Setting $setting)
    {
        $this->_em->remove($setting);
    }
    
}