<?php

namespace Hyper\DomainBundle\Repository\Application;

use Doctrine\ORM\EntityRepository;
use Hyper\Domain\Device\ApplicationRepository;
use Hyper\Domain\Application\Application;

/**
 * ApplicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DTApplicationRepository extends EntityRepository implements ApplicationRepository
{
    
}