<?php

namespace Hyper\DomainBundle\Repository\Client;

use Doctrine\ORM\EntityRepository;
use Hyper\Domain\Client\ClientAppTitleRepository;

/**
 * DTClientAppTitleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DTClientAppTitleRepository extends EntityRepository implements ClientAppTitleRepository
{

}
