<?php

namespace Hyper\DomainBundle\Repository\Promo_placement;

use Doctrine\ORM\EntityRepository;
use Hyper\Domain\Promo_placement\PromoPlacementRepository;
use Hyper\Domain\Promo_placement\PromoPlacement;

/**
 * PromoPlacementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DTPromoPlacementRepository extends EntityRepository implements PromoPlacementRepository
{
    public function save(PromoPlacement $promo_placement){
        $this->_em->persist($promo_placement);
    }
    
    public function completeTransaction(){        
        $this->_em->flush();        
    }
        
    
    public function findbyCriteria($field, $value)
    {
        $record = $this->findOneBy(array($field => $value));
        return $record;
    }
    
    public function getResultAndCount($page, $rpp)
    {
        $countQuery = $this->createQueryBuilder('pr')->select('count(pr.id)')->getQuery();
        $totalRows = $countQuery->getSingleScalarResult();

        $query = $this->createQueryBuilder('pr')->select('pr')->orderBy('pr.created', 'DESC')->getQuery();
        $offset = $rpp*($page-1);
        $rows = $query->setFirstResult($offset)->setMaxResults($rpp)->getResult(\Doctrine\ORM\Query::HYDRATE_OBJECT);
        return array(
            'rows' => $rows,
            'total' => $totalRows
        );
    }
    
    public function getLastRecord()
    {
        $query = $this->createQueryBuilder('promo')->select('promo')->orderBy('promo.created', 'DESC')->getQuery();
        $row = $query->setMaxResults(1)->getSingleResult(\Doctrine\ORM\Query::HYDRATE_OBJECT);
        return $row;
    }
    
    public function updatePlacement($appId, $placement_name)
    {
        $placement = $this->findOneBy(
            array('appId' => $appId)
        );
        
        $count = count($placement);
        
        if($count > 0)
        {
            $placement->setPlacementName($placement_name);
            $this->_em->flush();
            
            return "success";
        }        
        else
        {
            return "failed";
        }
    }
}